/***********************************************************************************************
*
* Copyright 2018 Infosys Ltd.
* Use of this source code is governed by MIT license that can be found in the LICENSE file or at
* https://opensource.org/licenses/MIT.
*
***********************************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.02 at 08:54:42 PM IST 
//


package com.infosys.utilities.nunit;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="clr-version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="culture" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cwd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="framework-version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="machine-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="os-architecture" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="os-version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="platform" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="uiculture" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="user" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="user-domain" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "value"
})
@XmlRootElement(name = "environment")
public class Environment {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "clr-version")
    protected String clrVersion;
    @XmlAttribute(name = "culture")
    protected String culture;
    @XmlAttribute(name = "cwd")
    protected String cwd;
    @XmlAttribute(name = "framework-version")
    protected String frameworkVersion;
    @XmlAttribute(name = "machine-name")
    protected String machineName;
    @XmlAttribute(name = "os-architecture")
    protected String osArchitecture;
    @XmlAttribute(name = "os-version")
    protected String osVersion;
    @XmlAttribute(name = "platform")
    protected String platform;
    @XmlAttribute(name = "uiculture")
    protected String uiculture;
    @XmlAttribute(name = "user")
    protected String user;
    @XmlAttribute(name = "user-domain")
    protected String userDomain;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the clrVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClrVersion() {
        return clrVersion;
    }

    /**
     * Sets the value of the clrVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClrVersion(String value) {
        this.clrVersion = value;
    }

    /**
     * Gets the value of the culture property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCulture() {
        return culture;
    }

    /**
     * Sets the value of the culture property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCulture(String value) {
        this.culture = value;
    }

    /**
     * Gets the value of the cwd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCwd() {
        return cwd;
    }

    /**
     * Sets the value of the cwd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCwd(String value) {
        this.cwd = value;
    }

    /**
     * Gets the value of the frameworkVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameworkVersion() {
        return frameworkVersion;
    }

    /**
     * Sets the value of the frameworkVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameworkVersion(String value) {
        this.frameworkVersion = value;
    }

    /**
     * Gets the value of the machineName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMachineName() {
        return machineName;
    }

    /**
     * Sets the value of the machineName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMachineName(String value) {
        this.machineName = value;
    }

    /**
     * Gets the value of the osArchitecture property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOsArchitecture() {
        return osArchitecture;
    }

    /**
     * Sets the value of the osArchitecture property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOsArchitecture(String value) {
        this.osArchitecture = value;
    }

    /**
     * Gets the value of the osVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOsVersion() {
        return osVersion;
    }

    /**
     * Sets the value of the osVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOsVersion(String value) {
        this.osVersion = value;
    }

    /**
     * Gets the value of the platform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * Sets the value of the platform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatform(String value) {
        this.platform = value;
    }

    /**
     * Gets the value of the uiculture property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUiculture() {
        return uiculture;
    }

    /**
     * Sets the value of the uiculture property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUiculture(String value) {
        this.uiculture = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUser(String value) {
        this.user = value;
    }

    /**
     * Gets the value of the userDomain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserDomain() {
        return userDomain;
    }

    /**
     * Sets the value of the userDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserDomain(String value) {
        this.userDomain = value;
    }

}
