/***********************************************************************************************
*
* Copyright 2018 Infosys Ltd.
* Use of this source code is governed by MIT license that can be found in the LICENSE file or at
* https://opensource.org/licenses/MIT.
*
***********************************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.02 at 08:54:42 PM IST 
//


package com.infosys.utilities.nunit;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}command-line"/>
 *         &lt;element ref="{}test-suite"/>
 *       &lt;/sequence>
 *       &lt;attribute name="asserts" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="clr-version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="duration" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="end-time" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="engine-version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="failed" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="inconclusive" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="passed" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="result" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="skipped" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="start-time" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="testcasecount" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *       &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "commandLine",
    "testSuite"
})
@XmlRootElement(name = "test-run")
public class TestRun {

    @XmlElement(name = "command-line", required = true)
    protected String commandLine;
    @XmlElement(name = "test-suite", required = true)
    protected TestSuite testSuite;
    @XmlAttribute(name = "asserts")
    protected Byte asserts;
    @XmlAttribute(name = "clr-version")
    protected String clrVersion;
    @XmlAttribute(name = "duration")
    protected Float duration;
    @XmlAttribute(name = "end-time")
    protected String endTime;
    @XmlAttribute(name = "engine-version")
    protected String engineVersion;
    @XmlAttribute(name = "failed")
    protected Byte failed;
    @XmlAttribute(name = "id")
    protected Byte id;
    @XmlAttribute(name = "inconclusive")
    protected Byte inconclusive;
    @XmlAttribute(name = "passed")
    protected Byte passed;
    @XmlAttribute(name = "result")
    protected String result;
    @XmlAttribute(name = "skipped")
    protected Byte skipped;
    @XmlAttribute(name = "start-time")
    protected String startTime;
    @XmlAttribute(name = "testcasecount")
    protected Byte testcasecount;
    @XmlAttribute(name = "total")
    protected Byte total;

    /**
     * Gets the value of the commandLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommandLine() {
        return commandLine;
    }

    /**
     * Sets the value of the commandLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommandLine(String value) {
        this.commandLine = value;
    }

    /**
     * Gets the value of the testSuite property.
     * 
     * @return
     *     possible object is
     *     {@link TestSuite }
     *     
     */
    public TestSuite getTestSuite() {
        return testSuite;
    }

    /**
     * Sets the value of the testSuite property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestSuite }
     *     
     */
    public void setTestSuite(TestSuite value) {
        this.testSuite = value;
    }

    /**
     * Gets the value of the asserts property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getAsserts() {
        return asserts;
    }

    /**
     * Sets the value of the asserts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setAsserts(Byte value) {
        this.asserts = value;
    }

    /**
     * Gets the value of the clrVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClrVersion() {
        return clrVersion;
    }

    /**
     * Sets the value of the clrVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClrVersion(String value) {
        this.clrVersion = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setDuration(Float value) {
        this.duration = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndTime(String value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the engineVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngineVersion() {
        return engineVersion;
    }

    /**
     * Sets the value of the engineVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngineVersion(String value) {
        this.engineVersion = value;
    }

    /**
     * Gets the value of the failed property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getFailed() {
        return failed;
    }

    /**
     * Sets the value of the failed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setFailed(Byte value) {
        this.failed = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setId(Byte value) {
        this.id = value;
    }

    /**
     * Gets the value of the inconclusive property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getInconclusive() {
        return inconclusive;
    }

    /**
     * Sets the value of the inconclusive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setInconclusive(Byte value) {
        this.inconclusive = value;
    }

    /**
     * Gets the value of the passed property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getPassed() {
        return passed;
    }

    /**
     * Sets the value of the passed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setPassed(Byte value) {
        this.passed = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResult(String value) {
        this.result = value;
    }

    /**
     * Gets the value of the skipped property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getSkipped() {
        return skipped;
    }

    /**
     * Sets the value of the skipped property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setSkipped(Byte value) {
        this.skipped = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartTime(String value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the testcasecount property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getTestcasecount() {
        return testcasecount;
    }

    /**
     * Sets the value of the testcasecount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setTestcasecount(Byte value) {
        this.testcasecount = value;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setTotal(Byte value) {
        this.total = value;
    }

}
