//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.27 at 01:33:12 PM IST 
//
package com.infosys.utilities.protractor;

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class ObjectFactory {
	public Testsuites createTestsuites() {
		return new Testsuites();
	}

	public Testsuites.Testsuite createTestsuitesTestsuite() {
		return new Testsuites.Testsuite();
	}

	public Testsuites.Testsuite.Testcase createTestsuitesTestsuiteTestcase() {
		return new Testsuites.Testsuite.Testcase();
	}
}
