//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.01 at 11:18:15 AM IST 
//
package com.infosys.utilities.checkmarx;

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class ObjectFactory {
	public CxXMLResults createCxXMLResults() {
		return new CxXMLResults();
	}

	public CxXMLResults.Query createCxXMLResultsQuery() {
		return new CxXMLResults.Query();
	}

	public CxXMLResults.Query.Result createCxXMLResultsQueryResult() {
		return new CxXMLResults.Query.Result();
	}

	public CxXMLResults.Query.Result.Path createCxXMLResultsQueryResultPath() {
		return new CxXMLResults.Query.Result.Path();
	}

	public CxXMLResults.Query.Result.Path.PathNode createCxXMLResultsQueryResultPathPathNode() {
		return new CxXMLResults.Query.Result.Path.PathNode();
	}

	public CxXMLResults.Query.Result.Path.PathNode.Snippet createCxXMLResultsQueryResultPathPathNodeSnippet() {
		return new CxXMLResults.Query.Result.Path.PathNode.Snippet();
	}

	public CxXMLResults.Query.Result.Path.PathNode.Snippet.Line createCxXMLResultsQueryResultPathPathNodeSnippetLine() {
		return new CxXMLResults.Query.Result.Path.PathNode.Snippet.Line();
	}
}
