//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.03 at 02:28:31 PM IST 
//
package com.infosys.utilities.seleniumtestng;

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class ObjectFactory {
	public Testng createTestngResults() {
		return new Testng();
	}

	public Testng.Suite createTestngResultsSuite() {
		return new Testng.Suite();
	}

	public Testng.Suite.Test createTestngResultsSuiteTest() {
		return new Testng.Suite.Test();
	}

	public Testng.Suite.Test.Class createTestngResultsSuiteTestClass() {
		return new Testng.Suite.Test.Class();
	}

	public Testng.Suite.Test.Class.TestMethod createTestngResultsSuiteTestClassTestMethod() {
		return new Testng.Suite.Test.Class.TestMethod();
	}
}
