/***********************************************************************************************
*
* Copyright 2018 Infosys Ltd.
* Use of this source code is governed by MIT license that can be found in the LICENSE file or at
* https://opensource.org/licenses/MIT.
*
***********************************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.03 at 02:28:31 PM IST 
//


package com.infosys.utilities.seleniumtestng;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reporter-output" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="suite">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="groups" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="test">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="class">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="test-method">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="reporter-output" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="signature" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                               &lt;attribute name="duration-ms" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                               &lt;attribute name="started-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                                               &lt;attribute name="finished-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="duration-ms" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="started-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                           &lt;attribute name="finished-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="duration-ms" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="started-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="finished-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="skipped" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="failed" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="total" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="passed" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reporterOutput",
    "suite"
})
@XmlRootElement(name = "testng-results")
public class Testng {

    @XmlElement(name = "reporter-output", required = true)
    protected String reporterOutput;
    @XmlElement(required = true)
    protected Testng.Suite suite;
    @XmlAttribute(name = "skipped")
    protected Integer skipped;
    @XmlAttribute(name = "failed")
    protected Integer failed;
    @XmlAttribute(name = "total")
    protected Integer total;
    @XmlAttribute(name = "passed")
    protected Integer passed;

    /**
     * Gets the value of the reporterOutput property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReporterOutput() {
        return reporterOutput;
    }

    /**
     * Sets the value of the reporterOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReporterOutput(String value) {
        this.reporterOutput = value;
    }

    /**
     * Gets the value of the suite property.
     * 
     * @return
     *     possible object is
     *     {@link Testng.Suite }
     *     
     */
    public Testng.Suite getSuite() {
        return suite;
    }

    /**
     * Sets the value of the suite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testng.Suite }
     *     
     */
    public void setSuite(Testng.Suite value) {
        this.suite = value;
    }

    /**
     * Gets the value of the skipped property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSkipped() {
        return skipped;
    }

    /**
     * Sets the value of the skipped property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSkipped(Integer value) {
        this.skipped = value;
    }

    /**
     * Gets the value of the failed property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getFailed() {
        return failed;
    }

    /**
     * Sets the value of the failed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setFailed(Integer value) {
        this.failed = value;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotal(Integer value) {
        this.total = value;
    }

    /**
     * Gets the value of the passed property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPassed() {
        return passed;
    }

    /**
     * Sets the value of the passed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPassed(Integer value) {
        this.passed = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="groups" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="test">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="class">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="test-method">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="reporter-output" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                     &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="signature" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                                     &lt;attribute name="duration-ms" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                                     &lt;attribute name="started-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *                                     &lt;attribute name="finished-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="duration-ms" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="started-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *                 &lt;attribute name="finished-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="duration-ms" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="started-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *       &lt;attribute name="finished-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "groups",
        "test"
    })
    public static class Suite {

        @XmlElement(required = true)
        protected String groups;
        @XmlElement(required = true)
        protected Testng.Suite.Test test;
        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "duration-ms")
        protected Integer durationMs;
        @XmlAttribute(name = "started-at")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar startedAt;
        @XmlAttribute(name = "finished-at")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar finishedAt;

        /**
         * Gets the value of the groups property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGroups() {
            return groups;
        }

        /**
         * Sets the value of the groups property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGroups(String value) {
            this.groups = value;
        }

        /**
         * Gets the value of the test property.
         * 
         * @return
         *     possible object is
         *     {@link Testng.Suite.Test }
         *     
         */
        public Testng.Suite.Test getTest() {
            return test;
        }

        /**
         * Sets the value of the test property.
         * 
         * @param value
         *     allowed object is
         *     {@link Testng.Suite.Test }
         *     
         */
        public void setTest(Testng.Suite.Test value) {
            this.test = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the durationMs property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getDurationMs() {
            return durationMs;
        }

        /**
         * Sets the value of the durationMs property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setDurationMs(Integer value) {
            this.durationMs = value;
        }

        /**
         * Gets the value of the startedAt property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getStartedAt() {
            return startedAt;
        }

        /**
         * Sets the value of the startedAt property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setStartedAt(XMLGregorianCalendar value) {
            this.startedAt = value;
        }

        /**
         * Gets the value of the finishedAt property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFinishedAt() {
            return finishedAt;
        }

        /**
         * Sets the value of the finishedAt property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFinishedAt(XMLGregorianCalendar value) {
            this.finishedAt = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="class">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="test-method">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="reporter-output" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                           &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="signature" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                           &lt;attribute name="duration-ms" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                           &lt;attribute name="started-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *                           &lt;attribute name="finished-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="duration-ms" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="started-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *       &lt;attribute name="finished-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "clazz"
        })
        public static class Test {

            @XmlElement(name = "class", required = true)
            protected List<Testng.Suite.Test.Class> clazz;
            @XmlAttribute(name = "name")
            protected String name;
            @XmlAttribute(name = "duration-ms")
            protected Integer durationMs;
            @XmlAttribute(name = "started-at")
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar startedAt;
            @XmlAttribute(name = "finished-at")
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar finishedAt;

            /**
             * Gets the value of the clazz property.
             * 
             * @return
             *     possible object is
             *     {@link Testng.Suite.Test.Class }
             *     
             */
          

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            public List<Testng.Suite.Test.Class> getClazz() {
				return clazz;
			}

			public void setClazz(List<Testng.Suite.Test.Class> clazz) {
				this.clazz = clazz;
			}

			/**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the durationMs property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getDurationMs() {
                return durationMs;
            }

            /**
             * Sets the value of the durationMs property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setDurationMs(Integer value) {
                this.durationMs = value;
            }

            /**
             * Gets the value of the startedAt property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getStartedAt() {
                return startedAt;
            }

            /**
             * Sets the value of the startedAt property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setStartedAt(XMLGregorianCalendar value) {
                this.startedAt = value;
            }

            /**
             * Gets the value of the finishedAt property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getFinishedAt() {
                return finishedAt;
            }

            /**
             * Sets the value of the finishedAt property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setFinishedAt(XMLGregorianCalendar value) {
                this.finishedAt = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="test-method">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="reporter-output" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *                 &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="signature" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *                 &lt;attribute name="duration-ms" type="{http://www.w3.org/2001/XMLSchema}int" />
             *                 &lt;attribute name="started-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
             *                 &lt;attribute name="finished-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "testMethod"
            })
            public static class Class {

                @XmlElement(name = "test-method", required = true)
                protected List<Testng.Suite.Test.Class.TestMethod> testMethod;
                @XmlAttribute(name = "name")
                protected String name;

                /**
                 * Gets the value of the testMethod property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Testng.Suite.Test.Class.TestMethod }
                 *     
                 */
                

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                public List<Testng.Suite.Test.Class.TestMethod> getTestMethod() {
					return testMethod;
				}

				public void setTestMethod(List<Testng.Suite.Test.Class.TestMethod> testMethod) {
					this.testMethod = testMethod;
				}

				/**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="reporter-output" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="signature" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *       &lt;attribute name="duration-ms" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *       &lt;attribute name="started-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
                 *       &lt;attribute name="finished-at" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "reporterOutput"
                })
                public static class TestMethod {

                    @XmlElement(name = "reporter-output", required = true)
                    protected String reporterOutput;
                    @XmlAttribute(name = "status")
                    protected String status;
                    @XmlAttribute(name = "signature")
                    protected String signature;
                    @XmlAttribute(name = "name")
                    protected String name;
                    @XmlAttribute(name = "duration-ms")
                    protected Integer durationMs;
                    @XmlAttribute(name = "started-at")
                    @XmlSchemaType(name = "dateTime")
                    protected XMLGregorianCalendar startedAt;
                    @XmlAttribute(name = "finished-at")
                    @XmlSchemaType(name = "dateTime")
                    protected XMLGregorianCalendar finishedAt;

                    /**
                     * Gets the value of the reporterOutput property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getReporterOutput() {
                        return reporterOutput;
                    }

                    /**
                     * Sets the value of the reporterOutput property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setReporterOutput(String value) {
                        this.reporterOutput = value;
                    }

                    /**
                     * Gets the value of the status property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getStatus() {
                        return status;
                    }

                    /**
                     * Sets the value of the status property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setStatus(String value) {
                        this.status = value;
                    }

                    /**
                     * Gets the value of the signature property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getSignature() {
                        return signature;
                    }

                    /**
                     * Sets the value of the signature property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setSignature(String value) {
                        this.signature = value;
                    }

                    /**
                     * Gets the value of the name property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the durationMs property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *     
                     */
                    public Integer getDurationMs() {
                        return durationMs;
                    }

                    /**
                     * Sets the value of the durationMs property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *     
                     */
                    public void setDurationMs(Integer value) {
                        this.durationMs = value;
                    }

                    /**
                     * Gets the value of the startedAt property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link XMLGregorianCalendar }
                     *     
                     */
                    public XMLGregorianCalendar getStartedAt() {
                        return startedAt;
                    }

                    /**
                     * Sets the value of the startedAt property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link XMLGregorianCalendar }
                     *     
                     */
                    public void setStartedAt(XMLGregorianCalendar value) {
                        this.startedAt = value;
                    }

                    /**
                     * Gets the value of the finishedAt property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link XMLGregorianCalendar }
                     *     
                     */
                    public XMLGregorianCalendar getFinishedAt() {
                        return finishedAt;
                    }

                    /**
                     * Sets the value of the finishedAt property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link XMLGregorianCalendar }
                     *     
                     */
                    public void setFinishedAt(XMLGregorianCalendar value) {
                        this.finishedAt = value;
                    }

                }

            }

        }

    }

}
