//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.03 at 02:28:31 PM IST 
//
package com.infosys.utilities.seleniumtestng;

import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "reporterOutput", "suite" })
@XmlRootElement(name = "testng-results")
public class Testng {
	@XmlElement(name = "reporter-output", required = true)
	protected String reporterOutput;
	@XmlElement(required = true)
	protected Testng.Suite suite;
	@XmlAttribute(name = "skipped")
	protected Integer skipped;
	@XmlAttribute(name = "failed")
	protected Integer failed;
	@XmlAttribute(name = "total")
	protected Integer total;
	@XmlAttribute(name = "passed")
	protected Integer passed;

	public String getReporterOutput() {
		return reporterOutput;
	}

	public void setReporterOutput(String value) {
		this.reporterOutput = value;
	}

	public Testng.Suite getSuite() {
		return suite;
	}

	public void setSuite(Testng.Suite value) {
		this.suite = value;
	}

	public Integer getSkipped() {
		return skipped;
	}

	public void setSkipped(Integer value) {
		this.skipped = value;
	}

	public Integer getFailed() {
		return failed;
	}

	public void setFailed(Integer value) {
		this.failed = value;
	}

	public Integer getTotal() {
		return total;
	}

	public void setTotal(Integer value) {
		this.total = value;
	}

	public Integer getPassed() {
		return passed;
	}

	public void setPassed(Integer value) {
		this.passed = value;
	}

	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "groups", "test" })
	public static class Suite {
		@XmlElement(required = true)
		protected String groups;
		@XmlElement(required = true)
		protected Testng.Suite.Test test;
		@XmlAttribute(name = "name")
		protected String name;
		@XmlAttribute(name = "duration-ms")
		protected Integer durationMs;
		@XmlAttribute(name = "started-at")
		@XmlSchemaType(name = "dateTime")
		protected XMLGregorianCalendar startedAt;
		@XmlAttribute(name = "finished-at")
		@XmlSchemaType(name = "dateTime")
		protected XMLGregorianCalendar finishedAt;

		public String getGroups() {
			return groups;
		}

		public void setGroups(String value) {
			this.groups = value;
		}

		public Testng.Suite.Test getTest() {
			return test;
		}

		public void setTest(Testng.Suite.Test value) {
			this.test = value;
		}

		public String getName() {
			return name;
		}

		public void setName(String value) {
			this.name = value;
		}

		public Integer getDurationMs() {
			return durationMs;
		}

		public void setDurationMs(Integer value) {
			this.durationMs = value;
		}

		public XMLGregorianCalendar getStartedAt() {
			return startedAt;
		}

		public void setStartedAt(XMLGregorianCalendar value) {
			this.startedAt = value;
		}

		public XMLGregorianCalendar getFinishedAt() {
			return finishedAt;
		}

		public void setFinishedAt(XMLGregorianCalendar value) {
			this.finishedAt = value;
		}

		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "clazz" })
		public static class Test {
			@XmlElement(name = "class", required = true)
			protected List<Testng.Suite.Test.Class> clazz;
			@XmlAttribute(name = "name")
			protected String name;
			@XmlAttribute(name = "duration-ms")
			protected Integer durationMs;
			@XmlAttribute(name = "started-at")
			@XmlSchemaType(name = "dateTime")
			protected XMLGregorianCalendar startedAt;
			@XmlAttribute(name = "finished-at")
			@XmlSchemaType(name = "dateTime")
			protected XMLGregorianCalendar finishedAt;

			public String getName() {
				return name;
			}

			public List<Testng.Suite.Test.Class> getClazz() {
				return clazz;
			}

			public void setClazz(List<Testng.Suite.Test.Class> clazz) {
				this.clazz = clazz;
			}

			public void setName(String value) {
				this.name = value;
			}

			public Integer getDurationMs() {
				return durationMs;
			}

			public void setDurationMs(Integer value) {
				this.durationMs = value;
			}

			public XMLGregorianCalendar getStartedAt() {
				return startedAt;
			}

			public void setStartedAt(XMLGregorianCalendar value) {
				this.startedAt = value;
			}

			public XMLGregorianCalendar getFinishedAt() {
				return finishedAt;
			}

			public void setFinishedAt(XMLGregorianCalendar value) {
				this.finishedAt = value;
			}

			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "testMethod" })
			public static class Class {
				@XmlElement(name = "test-method", required = true)
				protected List<Testng.Suite.Test.Class.TestMethod> testMethod;
				@XmlAttribute(name = "name")
				protected String name;

				public String getName() {
					return name;
				}

				public List<Testng.Suite.Test.Class.TestMethod> getTestMethod() {
					return testMethod;
				}

				public void setTestMethod(List<Testng.Suite.Test.Class.TestMethod> testMethod) {
					this.testMethod = testMethod;
				}

				public void setName(String value) {
					this.name = value;
				}

				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "", propOrder = { "reporterOutput" })
				public static class TestMethod {
					@XmlElement(name = "reporter-output", required = true)
					protected String reporterOutput;
					@XmlAttribute(name = "status")
					protected String status;
					@XmlAttribute(name = "signature")
					protected String signature;
					@XmlAttribute(name = "name")
					protected String name;
					@XmlAttribute(name = "duration-ms")
					protected Integer durationMs;
					@XmlAttribute(name = "started-at")
					@XmlSchemaType(name = "dateTime")
					protected XMLGregorianCalendar startedAt;
					@XmlAttribute(name = "finished-at")
					@XmlSchemaType(name = "dateTime")
					protected XMLGregorianCalendar finishedAt;

					public String getReporterOutput() {
						return reporterOutput;
					}

					public void setReporterOutput(String value) {
						this.reporterOutput = value;
					}

					public String getStatus() {
						return status;
					}

					public void setStatus(String value) {
						this.status = value;
					}

					public String getSignature() {
						return signature;
					}

					public void setSignature(String value) {
						this.signature = value;
					}

					public String getName() {
						return name;
					}

					public void setName(String value) {
						this.name = value;
					}

					public Integer getDurationMs() {
						return durationMs;
					}

					public void setDurationMs(Integer value) {
						this.durationMs = value;
					}

					public XMLGregorianCalendar getStartedAt() {
						return startedAt;
					}

					public void setStartedAt(XMLGregorianCalendar value) {
						this.startedAt = value;
					}

					public XMLGregorianCalendar getFinishedAt() {
						return finishedAt;
					}

					public void setFinishedAt(XMLGregorianCalendar value) {
						this.finishedAt = value;
					}
				}
			}
		}
	}
}
