/***********************************************************************************************
*
* Copyright 2018 Infosys Ltd.
* Use of this source code is governed by MIT license that can be found in the LICENSE file or at
* https://opensource.org/licenses/MIT.
*
***********************************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.05 at 06:13:35 PM IST 
//

package com.infosys.utilities.coberturajava;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.infosys.Utils.Coverage package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _CoveragePackagesPackageClassesClassLinesLineConditions_QNAME = new QName("",
			"conditions");
	private final static QName _CoveragePackagesPackageClassesClassLinesLine_QNAME = new QName("", "line");
	private final static QName _CoveragePackagesPackageClassesClassMethodsMethod_QNAME = new QName("", "method");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: com.infosys.Utils.Coverage
	 * 
	 */
	

	/**
	 * Create an instance of {@link Coverage.Sources }
	 * 
	 */
	public Coverage.Sources createCoverageSources() {
		return new Coverage.Sources();
	}

	/**
	 * Create an instance of {@link Coverage.Packages }
	 * 
	 */
	public Coverage.Packages createCoveragePackages() {
		return new Coverage.Packages();
	}

	/**
	 * Create an instance of
	 * {@link Coverage.Packages.Package.Classes.Class.Methods }
	 * 
	 */
	public Coverage.Packages.Package.Classes.Class.Methods createCoveragePackagesPackageClassesClassMethods() {
		return new Coverage.Packages.Package.Classes.Class.Methods();
	}

	/**
	 * Create an instance of {@link Coverage.Packages.Package }
	 * 
	 */
	public Coverage.Packages.Package createCoveragePackagesPackage() {
		return new Coverage.Packages.Package();
	}

	/**
	 * Create an instance of
	 * {@link Coverage.Packages.Package.Classes.Class.Lines.Line.Conditions }
	 * 
	 */
	public Coverage.Packages.Package.Classes.Class.Lines.Line.Conditions createCoveragePackagesPackageClassesClassLinesLineConditions() {
		return new Coverage.Packages.Package.Classes.Class.Lines.Line.Conditions();
	}

	/**
	 * Create an instance of
	 * {@link Coverage.Packages.Package.Classes.Class.Methods.Method.Lines.Line }
	 * 
	 */
	public Coverage.Packages.Package.Classes.Class.Methods.Method.Lines.Line createCoveragePackagesPackageClassesClassMethodsMethodLinesLine() {
		return new Coverage.Packages.Package.Classes.Class.Methods.Method.Lines.Line();
	}

	/**
	 * Create an instance of {@link Coverage.Packages.Package.Classes }
	 * 
	 */
	public Coverage.Packages.Package.Classes createCoveragePackagesPackageClasses() {
		return new Coverage.Packages.Package.Classes();
	}

	/**
	 * Create an instance of
	 * {@link Coverage.Packages.Package.Classes.Class.Methods.Method.Lines.Line.Conditions.Condition }
	 * 
	 */
	public Coverage.Packages.Package.Classes.Class.Methods.Method.Lines.Line.Conditions.Condition createCoveragePackagesPackageClassesClassMethodsMethodLinesLineConditionsCondition() {
		return new Coverage.Packages.Package.Classes.Class.Methods.Method.Lines.Line.Conditions.Condition();
	}

	/**
	 * Create an instance of {@link Coverage }
	 * 
	 */
	public Coverage createCoverage() {
		return new Coverage();
	}

	/**
	 * Create an instance of
	 * {@link Coverage.Packages.Package.Classes.Class.Lines }
	 * 
	 */
	public Coverage.Packages.Package.Classes.Class.Lines createCoveragePackagesPackageClassesClassLines() {
		return new Coverage.Packages.Package.Classes.Class.Lines();
	}

	/**
	 * Create an instance of
	 * {@link Coverage.Packages.Package.Classes.Class.Lines.Line }
	 * 
	 */
	public Coverage.Packages.Package.Classes.Class.Lines.Line createCoveragePackagesPackageClassesClassLinesLine() {
		return new Coverage.Packages.Package.Classes.Class.Lines.Line();
	}

	/**
	 * Create an instance of
	 * {@link Coverage.Packages.Package.Classes.Class.Methods.Method.Lines }
	 * 
	 */
	public Coverage.Packages.Package.Classes.Class.Methods.Method.Lines createCoveragePackagesPackageClassesClassMethodsMethodLines() {
		return new Coverage.Packages.Package.Classes.Class.Methods.Method.Lines();
	}

	/**
	 * Create an instance of
	 * {@link Coverage.Packages.Package.Classes.Class.Methods.Method.Lines.Line.Conditions }
	 * 
	 */
	public Coverage.Packages.Package.Classes.Class.Methods.Method.Lines.Line.Conditions createCoveragePackagesPackageClassesClassMethodsMethodLinesLineConditions() {
		return new Coverage.Packages.Package.Classes.Class.Methods.Method.Lines.Line.Conditions();
	}

	/**
	 * Create an instance of
	 * {@link Coverage.Packages.Package.Classes.Class.Lines.Line.Conditions.Condition }
	 * 
	 */
	public Coverage.Packages.Package.Classes.Class.Lines.Line.Conditions.Condition createCoveragePackagesPackageClassesClassLinesLineConditionsCondition() {
		return new Coverage.Packages.Package.Classes.Class.Lines.Line.Conditions.Condition();
	}

	/**
	 * Create an instance of {@link Coverage.Packages.Package.Classes.Class }
	 * 
	 */
	public Coverage.Packages.Package.Classes.Class createCoveragePackagesPackageClassesClass() {
		return new Coverage.Packages.Package.Classes.Class();
	}

	/**
	 * Create an instance of
	 * {@link Coverage.Packages.Package.Classes.Class.Methods.Method }
	 * 
	 */
	public Coverage.Packages.Package.Classes.Class.Methods.Method createCoveragePackagesPackageClassesClassMethodsMethod() {
		return new Coverage.Packages.Package.Classes.Class.Methods.Method();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link Coverage.Packages.Package.Classes.Class.Lines.Line.Conditions }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "conditions", scope = Coverage.Packages.Package.Classes.Class.Lines.Line.class)
	public JAXBElement<Coverage.Packages.Package.Classes.Class.Lines.Line.Conditions> createCoveragePackagesPackageClassesClassLinesLineConditions(
			Coverage.Packages.Package.Classes.Class.Lines.Line.Conditions value) {
		return new JAXBElement<Coverage.Packages.Package.Classes.Class.Lines.Line.Conditions>(
				_CoveragePackagesPackageClassesClassLinesLineConditions_QNAME,
				Coverage.Packages.Package.Classes.Class.Lines.Line.Conditions.class,
				Coverage.Packages.Package.Classes.Class.Lines.Line.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link Coverage.Packages.Package.Classes.Class.Lines.Line }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "line", scope = Coverage.Packages.Package.Classes.Class.Lines.class)
	public JAXBElement<Coverage.Packages.Package.Classes.Class.Lines.Line> createCoveragePackagesPackageClassesClassLinesLine(
			Coverage.Packages.Package.Classes.Class.Lines.Line value) {
		return new JAXBElement<Coverage.Packages.Package.Classes.Class.Lines.Line>(
				_CoveragePackagesPackageClassesClassLinesLine_QNAME,
				Coverage.Packages.Package.Classes.Class.Lines.Line.class,
				Coverage.Packages.Package.Classes.Class.Lines.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link Coverage.Packages.Package.Classes.Class.Methods.Method }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "method", scope = Coverage.Packages.Package.Classes.Class.Methods.class)
	public JAXBElement<Coverage.Packages.Package.Classes.Class.Methods.Method> createCoveragePackagesPackageClassesClassMethodsMethod(
			Coverage.Packages.Package.Classes.Class.Methods.Method value) {
		return new JAXBElement<Coverage.Packages.Package.Classes.Class.Methods.Method>(
				_CoveragePackagesPackageClassesClassMethodsMethod_QNAME,
				Coverage.Packages.Package.Classes.Class.Methods.Method.class,
				Coverage.Packages.Package.Classes.Class.Methods.class, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}
	 * {@link Coverage.Packages.Package.Classes.Class.Methods.Method.Lines.Line.Conditions }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "conditions", scope = Coverage.Packages.Package.Classes.Class.Methods.Method.Lines.Line.class)
	public JAXBElement<Coverage.Packages.Package.Classes.Class.Methods.Method.Lines.Line.Conditions> createCoveragePackagesPackageClassesClassMethodsMethodLinesLineConditions(
			Coverage.Packages.Package.Classes.Class.Methods.Method.Lines.Line.Conditions value) {
		return new JAXBElement<Coverage.Packages.Package.Classes.Class.Methods.Method.Lines.Line.Conditions>(
				_CoveragePackagesPackageClassesClassLinesLineConditions_QNAME,
				Coverage.Packages.Package.Classes.Class.Methods.Method.Lines.Line.Conditions.class,
				Coverage.Packages.Package.Classes.Class.Methods.Method.Lines.Line.class, value);
	}

}
