/***********************************************************************************************
*
* Copyright 2018 Infosys Ltd.
* Use of this source code is governed by MIT license that can be found in the LICENSE file or at
* https://opensource.org/licenses/MIT.
*
***********************************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.18 at 02:39:31 AM IST 
//


package com.infosys.utilities.jmeter;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.infosys.Utils.JMeter package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.infosys.Utils.JMeter
     * 
     */
    

    /**
     * Create an instance of {@link TestResults }
     * 
     */
    public TestResults createTestResults() {
        return new TestResults();
    }

    /**
     * Create an instance of {@link TestResults.HttpSample }
     * 
     */
    public TestResults.HttpSample createTestResultsHttpSample() {
        return new TestResults.HttpSample();
    }

    /**
     * Create an instance of {@link TestResults.Sample }
     * 
     */
    public TestResults.Sample createTestResultsSample() {
        return new TestResults.Sample();
    }

    /**
     * Create an instance of {@link TestResults.HttpSample.AssertionResult }
     * 
     */
    public TestResults.HttpSample.AssertionResult createTestResultsHttpSampleAssertionResult() {
        return new TestResults.HttpSample.AssertionResult();
    }

}
