//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.12 at 08:54:28 PM IST 
//
package com.infosys.utilities.junitgo;

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class ObjectFactory {
	public Testsuites createTestsuites() {
		return new Testsuites();
	}

	public Testsuites.Testsuite createTestsuitesTestsuite() {
		return new Testsuites.Testsuite();
	}

	public Testsuites.Testsuite.Testcase createTestsuitesTestsuiteTestcase() {
		return new Testsuites.Testsuite.Testcase();
	}

	public Testsuites.Testsuite.Properties createTestsuitesTestsuiteProperties() {
		return new Testsuites.Testsuite.Properties();
	}

	public Testsuites.Testsuite.Testcase.Failure createTestsuitesTestsuiteTestcaseFailure() {
		return new Testsuites.Testsuite.Testcase.Failure();
	}

	public Testsuites.Testsuite.Properties.Property createTestsuitesTestsuitePropertiesProperty() {
		return new Testsuites.Testsuite.Properties.Property();
	}
}
