/***********************************************************************************************
*
* Copyright 2018 Infosys Ltd.
* Use of this source code is governed by MIT license that can be found in the LICENSE file or at
* https://opensource.org/licenses/MIT.
*
***********************************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.12 at 08:54:28 PM IST 
//


package com.infosys.utilities.junitgo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.infosys.Utils.JunitGo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.infosys.Utils.JunitGo
     * 
     */
    

    /**
     * Create an instance of {@link Testsuites }
     * 
     */
    public Testsuites createTestsuites() {
        return new Testsuites();
    }

    /**
     * Create an instance of {@link Testsuites.Testsuite }
     * 
     */
    public Testsuites.Testsuite createTestsuitesTestsuite() {
        return new Testsuites.Testsuite();
    }

    /**
     * Create an instance of {@link Testsuites.Testsuite.Testcase }
     * 
     */
    public Testsuites.Testsuite.Testcase createTestsuitesTestsuiteTestcase() {
        return new Testsuites.Testsuite.Testcase();
    }

    /**
     * Create an instance of {@link Testsuites.Testsuite.Properties }
     * 
     */
    public Testsuites.Testsuite.Properties createTestsuitesTestsuiteProperties() {
        return new Testsuites.Testsuite.Properties();
    }

    /**
     * Create an instance of {@link Testsuites.Testsuite.Testcase.Failure }
     * 
     */
    public Testsuites.Testsuite.Testcase.Failure createTestsuitesTestsuiteTestcaseFailure() {
        return new Testsuites.Testsuite.Testcase.Failure();
    }

    /**
     * Create an instance of {@link Testsuites.Testsuite.Properties.Property }
     * 
     */
    public Testsuites.Testsuite.Properties.Property createTestsuitesTestsuitePropertiesProperty() {
        return new Testsuites.Testsuite.Properties.Property();
    }

}
