{
 "title": "Application Dashboard v2 PG",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Application",
    "label": "Application",
    "query": "select application_name  from appinfo"
   }
  ]
 },
 "panels": [
  { "title": "Pipeline Info", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pipelines",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "Build_Info",
     "query": "SELECT count(\"Pipeline_Name\") FROM \"Build_Info\" WHERE \"Application_Name\" =~ /^$Application$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "Pipeline_Name" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "Application_Name", "operator": "=~", "value": "/^$Application$/" }
     ],
     "target": "select count(id),max(created_at) from appinfo where application_name='$Application'",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Total jobs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "Build_Info",
     "query": "SELECT count(\"Pipeline_Name\") FROM \"Build_Info\" WHERE \"Application_Name\" =~ /^$Application$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "Pipeline_Name" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "Application_Name", "operator": "=~", "value": "/^$Application$/" }
     ],
     "target": "select count(appid),max(created_at) from buildinfo where appid in (select id from appinfo where application_name='$Application')",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Successfull",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "Build_Info",
     "query": "SELECT count(\"Pipeline_Name\") FROM \"Build_Info\" WHERE \"Application_Name\" =~ /^$Application$/ AND \"Build_status\" =~ /.*SUCCESS.*/ AND $timeFilter",
     "select": [
      [
       { "params": [ "Pipeline_Name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "Application_Name", "operator": "=~", "value": "/^$Application/" }
     ],
     "target": "select count(appid),max(created_at) from buildinfo where buildstatus='SUCCESS' and appid in (select id from appinfo where application_name='$Application')",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Pipeline_Name\") FROM \"Build_Info\" WHERE \"Application_Name\" =~ /^$Application$/ AND \"Build_status\" =~ /.*FAILURE.*/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select count(appid),max(created_at) from buildinfo where buildstatus='FAILURE' and appid in (select id from appinfo where application_name='$Application')",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Application Score",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Build_Info",
     "query": "SELECT mean(\"Score\") FROM \"Build_Info\" WHERE \"Application_Name\" =~ /^$Application$/",
     "select": [
      [
       { "params": [ "Score" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Application_Name", "operator": "=~", "value": "/^$Application$/" }
     ],
     "target": "select round(avg(score),2),max(created_at) from buildinfo where appid in (select id from appinfo where application_name ='$Application')",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Commits per Engineer",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select lastmodifiedby as Developer,count(*) as commits_per_pipeline from scminfo group by appid,lastmodifiedby having appid in (select id from appinfo where application_name='$Application')",
     "type": "table"
    }
   ]
  },
  {
   "title": "Total SCM Checkouts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Application_Name\") FROM \"Build_Info\" WHERE \"Application_Name\" =~ /.*$Application$.*/ AND \"Stage_Name\" =~ /.*SCM.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select count(appid),max(created_at) from buildinfo where stagename='SCM' and appid in (select id from appinfo where application_name='$Application')",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Duration Trend",
   "type": "graph",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 6 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "alias": "Build Time",
     "measurement": "Build_Info",
     "query": "SELECT \"Build_Time\" FROM \"Build_Info\" WHERE \"Application_Name\" =~ /^$Application$/ AND \"Stage_Name\" =~ /.*SCM.*/ AND $timeFilter",
     "select": [
      [
       { "params": [ "Build_Time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Application_Name", "operator": "=~", "value": "/^$Application$/" }
     ],
     "target": "select buildtime,created_at from buildinfo where stagename='SCM'  and appid in (select id from appinfo where application_name='$Application')",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Failed Checkouts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Application_Name\") FROM \"Build_Info\" WHERE \"Application_Name\" =~ /.*$Application.*/ AND \"Stage_Name\" =~ /.*SCM.*/ AND \"Build_status\" !~ /.*SUCCESS.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select count(appid),max(created_at) from buildinfo where stagename='SCM' and appid in (select id from appinfo where application_name='$Application') and buildstatus='FAILURE'",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Successful Checkouts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Application_Name\") FROM \"Build_Info\" WHERE \"Application_Name\" =~ /.*$Application.*/ AND \"Stage_Name\" =~ /.*SCM.*/ AND \"Build_status\" =~ /.*SUCCESS.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select count(appid),max(created_at) from buildinfo where stagename='SCM' and appid in (select id from appinfo where application_name='$Application') and buildstatus='SUCCESS'",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Total Builds",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Application_Name\") FROM \"Build_Info\" WHERE \"Application_Name\" =~ /.*$Application.*/ AND \"Stage_Name\" =~ /.*Build.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select count(appid),max(created_at) from buildinfo where stagename='Build' and appid in (select id from appinfo where application_name='$Application')",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Duration Trend",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Build_Time\" FROM \"Build_Info\" WHERE \"Application_Name\" =~ /.*$Application/ AND \"Stage_Name\" =~ /.*Build.*/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select buildtime,created_at,buildtime from buildinfo where stagename='Build'  and appid in (select id from appinfo where application_name='$Application')",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Failed Builds",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Application_Name\") FROM \"Build_Info\" WHERE \"Application_Name\" =~ /.*$Application.*/ AND \"Stage_Name\" =~ /.*Build.*/ AND \"Build_status\" !~ /.*SUCCESS.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select count(appid),max(created_at) from buildinfo where stagename='Build' and appid in (select id from appinfo where application_name='$Application') and buildstatus='FAILURE'",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Successful Builds",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Application_Name\") FROM \"Build_Info\" WHERE \"Application_Name\" =~ /.*$Application.*/ AND \"Stage_Name\" =~ /.*Build.*/ AND \"Build_status\" =~ /.*SUCCESS.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select count(appid),max(created_at) from buildinfo where stagename='Build' and appid in (select id from appinfo where application_name='$Application') and buildstatus='SUCCESS'",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Total Tests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Application_Name\") FROM \"Build_Info\" WHERE \"Application_Name\" =~ /.*$Application.*/ AND \"Stage_Name\" =~ /.*Test.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select count(appid),max(created_at) from buildinfo where stagename like '%Test%' and appid in (select id from appinfo where application_name='$Application')",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Duration Trend",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 15 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "alias": "Test Durations",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Build_Time\" FROM \"Build_Info\" WHERE \"Application_Name\" =~ /.*$Application/ AND \"Stage_Name\" =~ /.*Test.*/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select buildtime,created_at from buildinfo where stagename like '%Test%'  and appid in (select id from appinfo where application_name='$Application' order by appid desc)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Failed Test",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Application_Name\") FROM \"Build_Info\" WHERE \"Application_Name\" =~ /.*$Application.*/ AND \"Stage_Name\" =~ /.*Test.*/ AND \"Build_status\" !~ /.*SUCCESS.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select count(appid),max(created_at) from buildinfo where stagename like '%Test%' and appid in (select id from appinfo where application_name='$Application') and buildstatus='FAILURE'",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Successful Tests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Application_Name\") FROM \"Build_Info\" WHERE \"Application_Name\" =~ /.*$Application.*/ AND \"Stage_Name\" =~ /.*Test.*/ AND \"Build_status\" =~ /.*SUCCESS.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select count(appid),max(created_at) from buildinfo where stagename like '%Test%' and appid in (select id from appinfo where application_name='$Application') and buildstatus!='FAILURE'",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Total Deploys",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Application_Name\") FROM \"Build_Info\" WHERE \"Application_Name\" =~ /.*$Application.*/ AND \"Stage_Name\" =~ /.*Deploy.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select count(appid),max(created_at) from buildinfo where stagename like '%Deploy%' and appid in (select id from appinfo where application_name='$Application')",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Duration Trend",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 20 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Build_Time\" FROM \"Build_Info\" WHERE \"Application_Name\" =~ /.*$Application/ AND \"Stage_Name\" =~ /.*Deploy.*/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select buildtime,created_at,buildtime from buildinfo where stagename like '%Deploy%'  and appid in (select id from appinfo where application_name='$Application')",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Successful Deploys",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 14, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Application_Name\") FROM \"Build_Info\" WHERE \"Application_Name\" =~ /.*$Application.*/ AND \"Stage_Name\" =~ /.*Deploy.*/ AND \"Build_status\" =~ /.*SUCCESS.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select count(appid),max(created_at) from buildinfo where stagename like '%Deploy%' and appid in (select id from appinfo where application_name='$Application') and buildstatus='SUCCESS'",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Failed Deploys",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Application_Name\") FROM \"Build_Info\" WHERE \"Application_Name\" =~ /.*$Application.*/ AND \"Stage_Name\" =~ /.*Deploy.*/ AND \"Build_status\" !~ /.*SUCCESS.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select count(appid),max(created_at) from buildinfo where stagename like '%Deploy%' and appid in (select id from appinfo where application_name='$Application') and buildstatus='FAILURE'",
     "type": "timeserie"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 25 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "SELECT count(*),max(created_at) from buildinfo where  DATE_PART('day',CURRENT_TIMESTAMP::timestamp-created_at::timestamp )<=7 and appid in (select id from appinfo where application_name='$Application') and stagename like '%Deploy%'",
     "type": "timeserie"
    }
   ]
  }
 ]
}