{
 "title": "Developer Dashboard v2 PG",
 "time": { "from": "2018-01-29T09:14:25.854Z", "to": "2018-01-29T09:24:25.854Z" },
 "templating": {
  "list": [
   {
    "name": "Application",
    "label": "Application",
    "query": "select application_name from appinfo order by created_at desc"
   },
   {
    "name": "Pipeline",
    "label": "Pipeline",
    "query": "select pipeline_name from appinfo where application_name ='$Application'"
   },
   {
    "name": "Build_Number",
    "label": "Build_Number",
    "query": "select distinct pipelineno from buildinfo where appid=(select id from appinfo where application_name='$Application' and pipeline_name='$Pipeline')"
   }
  ]
 },
 "panels": [
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SCM Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Build_Info",
     "query": "SELECT last(\"Build_status\") FROM \"Build_Info\" WHERE \"Pipeline_Name\" =~ /.*$Pipeline.*/ AND \"Application_Name\" =~ /^$Application.*/ AND \"Stage_Name\" =~ /.*SCM.*/ AND \"PipelineNo\" =~ /^$Build_Number.*/ AND $timeFilter",
     "select": [
      [
       { "params": [ "Build_status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Application_Name", "operator": "=~", "value": "/.*$Pipeline.*/" },
      { "condition": "AND", "key": "Application_Name", "operator": "=~", "value": "/^$Application.*/" },
      { "condition": "AND", "key": "Application_Name", "operator": "=~", "value": "/.*.SCM*/" }
     ],
     "target": "select buildstatus,created_at from buildinfo where appid=(select id from appinfo where application_name='$Application' and pipeline_name ='$Pipeline') and pipelineno='$Build_Number' and stagename like '%SCM%'",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Build Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "select buildstatus,created_at from buildinfo where appid=(select id from appinfo where application_name='$Application' and pipeline_name ='$Pipeline')  and pipelineno='$Build_Number' and stagename like '%Build%'",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Deploy Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Build_status\" FROM \"Build_Info\" WHERE \"Pipeline_Name\" =~ /.*$Pipeline.*/ AND \"Application_Name\" =~ /^$Application.*/ AND \"Stage_Name\" =~ /.*Deploy.*/ AND \"PipelineNo\" =~ /^$Build_Number.*/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select buildstatus,created_at from buildinfo where appid=(select id from appinfo where application_name='$Application' and pipeline_name ='$Pipeline')  and pipelineno='$Build_Number' and stagename like '%Deploy%'",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Test Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Build_status\" FROM \"Build_Info\" WHERE \"Pipeline_Name\" =~ /.*$Pipeline.*/ AND \"Application_Name\" =~ /^$Application.*/ AND \"Stage_Name\" =~ /.*Test.*/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select buildstatus,created_at from buildinfo where appid=(select id from appinfo where application_name='$Application' and pipeline_name ='$Pipeline')  and pipelineno='$Build_Number' and stagename like '%Test%'",
     "type": "timeserie"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "SCM duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "format": "dtdurationms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT Build_Time,timestamp FROM Build_Info WHERE Pipeline_Name ='$Pipeline' AND Application_Name ='$Application' AND Stage_Name ='SCM' AND PipelineNo='$Build_Number'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "SELECT buildtime,created_at FROM buildinfo WHERE appid=(select id from appinfo where application_name='$Application' and pipeline_name ='$Pipeline')  and pipelineno='$Build_Number' and stagename like '%SCM%'",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Build duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 5 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"Build_Time\") FROM \"Build_Info\" WHERE \"Pipeline_Name\" =~ /.*$Pipeline.*/ AND \"Application_Name\" =~ /.*$Application.*/ AND \"Stage_Name\" =~ /(?i).*BUILD.*/ AND PipelineNo=~ /^.*$Build_Number.*/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "SELECT buildtime,created_at FROM buildinfo WHERE appid=(select id from appinfo where application_name='$Application' and pipeline_name ='$Pipeline')  and pipelineno='$Build_Number' and stagename like '%Build%'",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Deploy duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 10, "y": 5 },
   "format": "dtdurationms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"Build_Time\") FROM \"Build_Info\" WHERE \"Pipeline_Name\" =~ /.*$Pipeline.*/ AND \"Application_Name\" =~ /.*$Application.*/ AND \"Stage_Name\" =~ /(?i).*DEPLOY.*/AND PipelineNo=~ /^.*$Build_Number.*/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "SELECT sum(buildtime),max(created_at) FROM buildinfo WHERE appid=(select id from appinfo where application_name='$Application' and pipeline_name ='$Pipeline')  and pipelineno='$Build_Number' and stagename like '%Deploy%'",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Test duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "format": "dtdurationms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"Build_Time\") FROM \"Build_Info\" WHERE \"Pipeline_Name\" =~ /.*$Pipeline.*/ AND \"Application_Name\" =~ /.*$Application.*/ AND \"Stage_Name\" =~ /(?i).*Test.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "SELECT sum(buildtime),max(created_at) FROM buildinfo WHERE appid=(select id from appinfo where application_name='$Application' and pipeline_name ='$Pipeline')  and pipelineno='$Build_Number'and stagename like '%Test%'",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Total Duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "TimeTrackerAppInfo",
     "select": [
      [
       { "params": [ "TotalDurationOfApplication" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Application_Name", "operator": "=~", "value": "/^$Application$/" },
      { "condition": "AND", "key": "Pipeline_Name", "operator": "=~", "value": "/^$Pipeline$/" }
     ],
     "target": "select sum(buildtime),max(created_at)from buildinfo group by appid,pipelineno having appid=(select id from appinfo where application_name='$Application' and pipeline_name ='$Pipeline')  and pipelineno='$Build_Number'",
     "type": "timeserie"
    }
   ]
  },
  { "title": "Coverage Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Zero coverage classes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"className\") FROM \"CoverageDetails_Info\" WHERE \"PipelineNo\" =~ /^$Build_Number$/ AND \"Application_Name\" =~ /^$Application$/ AND \"Pipeline_Name\" =~ /^$Pipeline$/  AND lineCoverage = 0",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select count(classname) , max(created_at) from codecoverage where appid=(select id from appinfo where application_name='$Application' and pipeline_name ='$Pipeline')  and pipelineno='$Build_Number' and linecoverage=0",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "0-50% coverage classes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"className\") FROM \"CoverageDetails_Info\" WHERE \"PipelineNo\" =~ /^$Build_Number$/ AND \"Application_Name\" =~ /^$Application$/ AND \"Pipeline_Name\" =~ /^$Pipeline$/  AND lineCoverage > 0 AND lineCoverage <= 50",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select count(classname) ,max(created_at) from codecoverage where appid=(select id from appinfo where application_name='$Application' and pipeline_name ='$Pipeline')  and pipelineno='$Build_Number' and linecoverage>0 and linecoverage<=50",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "50-100% coverage classes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"className\") FROM \"CoverageDetails_Info\" WHERE \"PipelineNo\" =~ /^$Build_Number$/ AND \"Application_Name\" =~ /^$Application$/ AND \"Pipeline_Name\" =~ /^$Pipeline$/  AND lineCoverage >= 50 AND lineCoverage <= 100",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select count(classname) ,max(created_at) from codecoverage where appid=(select id from appinfo where application_name='$Application' and pipeline_name ='$Pipeline')  and pipelineno='$Build_Number' and linecoverage>50 and linecoverage<=100",
     "type": "timeserie"
    }
   ]
  },
  { "title": "Code Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "High Severity",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "format": "none",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Rule\") FROM \"CodeAnalysis_Info\" WHERE \"Pipeline_Name\" =~ /.*$Pipeline.*/ AND \"Application_Name\" =~ /.*$Application.*/ AND \"Severity\" =~ /.*high.*/  AND PipelineNo=~ /^.*$Build_Number.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select count(rulename),max(created_at) from codeanalysis where appid=(select id from appinfo where application_name='$Application' and pipeline_name ='$Pipeline') and pipelineno='$Build_Number' and severity='high'",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "medium Severity",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 14 },
   "format": "none",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Rule\") FROM \"CodeAnalysis_Info\" WHERE \"Pipeline_Name\" =~ /.*$Pipeline.*/ AND \"Application_Name\" =~ /.*$Application.*/ AND \"Severity\" =~ /.*medium.*/  AND PipelineNo=~ /^.*$Build_Number.*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select count(rulename),max(created_at) from codeanalysis where appid=(select id from appinfo where application_name='$Application' and pipeline_name ='$Pipeline') and pipelineno='$Build_Number' and severity='medium'",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Low Severity violations",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 14 },
   "format": "none",
   "targets": [
    {
     "target": "select count(rulename),max(created_at) from codeanalysis where appid=(select id from appinfo where application_name='$Application' and pipeline_name ='$Pipeline') and pipelineno='$Build_Number'",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Top Rules violated",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select  rulename,count(*) as count,category from codeanalysis  group by severity,rulename,appid,pipelineno,category having appid=(select id from appinfo where application_name='$Application' and pipeline_name ='$Pipeline') and pipelineno='$Build_Number' order by count(*) desc limit 5",
     "type": "table"
    }
   ]
  },
  {
   "title": "Test Results including unit tests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Total Tests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "TestInfo_Chirag_latest",
     "query": "SELECT count(\"Application_Name\") FROM \"TestAnalysis_Info\" WHERE \"Pipeline_Name\" =~ /.*$Pipeline.*/ AND \"Application_Name\" =~ /^$Application.*/  AND PipelineNo=~ /^.*$Build_Number.*/AND $timeFilter",
     "select": [
      [
       { "params": [ "Application_Name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "Application_Name", "operator": "=~", "value": "/.*$Pipeline.*/" },
      { "condition": "AND", "key": "Application_Name", "operator": "=~", "value": "/^$Application.*/" }
     ],
     "target": "select count(*),max(created_at) from testanalysis where  appid=(select id from appinfo where application_name='$Application' and pipeline_name ='$Pipeline') and pipelineno='$Build_Number'",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"Application_Name\") FROM \"TestAnalysis_Info\" WHERE \"Pipeline_Name\" =~ /.*$Pipeline.*/ AND \"Test_Status\" !~ /(?i).*Passed.*/ AND \"Application_Name\" =~ /^$Application.*/  AND PipelineNo=~ /^.*$Build_Number.*/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select count(*),max(created_at) from testanalysis where  appid=(select id from appinfo where application_name='$Application' and pipeline_name ='$Pipeline') and pipelineno='$Build_Number' and( status like '%Fail%' or status like '%FAILURE%' or status like '%fail%')",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Passed Tests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "TestInfo_Chirag_latest",
     "query": "SELECT count(\"Application_Name\") FROM \"TestAnalysis_Info\" WHERE \"Pipeline_Name\" =~ /.*$Pipeline.*/ AND \"Application_Name\" =~ /^$Application.*/  AND PipelineNo=~ /^.*$Build_Number.*/AND $timeFilter",
     "select": [
      [
       { "params": [ "Application_Name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "Application_Name", "operator": "=~", "value": "/.*$Pipeline.*/" },
      { "condition": "AND", "key": "Application_Name", "operator": "=~", "value": "/^$Application.*/" }
     ],
     "target": "select count(*),max(created_at) from testanalysis where appid=(select id from appinfo where application_name='$Application' and pipeline_name ='$Pipeline') and pipelineno='$Build_Number' and (status='SUCCESS' or status='Passed' or status ='passed')",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Test Results info",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select category,status,duration,message from testanalysis where appid=(select id from appinfo where application_name='$Application' and pipeline_name ='$Pipeline') and pipelineno='$Build_Number'",
     "type": "table"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  { "title": "Commit info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Commits info",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 27 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select  lastmodifiedon as committed_on,lastmodifiedby as committed_by,commitmessage as commit_message from scminfo where appid=(select id from appinfo where application_name='$Application' and pipeline_name='$Pipeline')and pipelineno='$Build_Number'",
     "type": "table"
    }
   ]
  },
  {
   "title": "No of Commits",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 27 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "select  count(*),max(created_at)from scminfo where appid=(select id from appinfo where application_name='$Application' and pipeline_name='$Pipeline')and pipelineno='$Build_Number'",
     "type": "timeserie"
    }
   ]
  }
 ]
}