{
 "title": "UnifiedApps",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Code Analysis",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "analysisscoreviolations", "type": "timeserie" }
   ]
  },
  {
   "title": "Code Coverage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "analysisscorecoverage", "type": "timeserie" }
   ]
  },
  {
   "title": "Application Deploy Status",
   "type": "savantly-heatmap-panel",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "format": "none",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n",
     "target": "deploytrend",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Applications Build Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "buildtrend", "type": "timeserie" }
   ]
  }
 ]
}