//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.06 at 10:10:32 AM IST 
//


package com.infosys.utilities.sahi;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="suite">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="suiteSummary">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="SUITEREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SUITENAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SUITEPATH" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="STARTTIME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ENDTIME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SUITESTATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="TOTALCOUNT" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="PASSEDCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="FAILEDCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="TIMETAKEN" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="BROWSERTYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SUITEINFO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="USERDEFINEDID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="TCCOUNT" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="TCPASSED" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="TCFAILED" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="MACHINENAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="PARENTSUITEID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SKIPPEDCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="ABORTEDCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="ORIGINALPATH" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ANDROIDDEVICE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="IOSDEVICE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="NOTSUPPORTEDCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="HEALEDCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="COMMENTDATA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="nodes">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="node">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="SUITEREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="HOSTNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="PORT" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                                 &lt;element name="SCRIPTCOUNT" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="scriptSummaries">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="summary" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                                       &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                       &lt;element name="SCRIPTREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="OUTPUT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ARTIFACT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="SCREENSHOT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="SCRIPTNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="SUITENAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="SUITEREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="TOTALSTEPS" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                       &lt;element name="FAILURES" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="ERRORS" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="TIMETAKEN" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="NODEHOST" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="NODEPORT" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                       &lt;element name="SCRIPTSTATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="LOADCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="TCCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="TCPASSED" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="TCFAILED" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="SCRIPTRELPATH" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="STARTURL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                                       &lt;element name="LAUNCHERID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="SCRIPTARGS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="STARTTIME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="SUITEID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="SUITEINFO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/choice>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="testCaseSummaries">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="testCaseSummary" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                       &lt;element name="TESTCASEREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="SCRIPTREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="SUITEREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="TCSTATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="TIMETAKEN" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="SCRIPTNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="FAILUREMESSAGE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "suite"
})
@XmlRootElement(name = "suites")
public class Suites {

    @XmlElement(required = true)
    protected Suites.Suite suite;

    /**
     * Gets the value of the suite property.
     * 
     * @return
     *     possible object is
     *     {@link Suites.Suite }
     *     
     */
    public Suites.Suite getSuite() {
        return suite;
    }

    /**
     * Sets the value of the suite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Suites.Suite }
     *     
     */
    public void setSuite(Suites.Suite value) {
        this.suite = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="suiteSummary">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="SUITEREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SUITENAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SUITEPATH" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="STARTTIME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ENDTIME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SUITESTATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="TOTALCOUNT" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="PASSEDCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="FAILEDCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="TIMETAKEN" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="BROWSERTYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SUITEINFO" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="USERDEFINEDID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="TCCOUNT" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="TCPASSED" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="TCFAILED" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="MACHINENAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="PARENTSUITEID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SKIPPEDCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="ABORTEDCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="ORIGINALPATH" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ANDROIDDEVICE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="IOSDEVICE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="NOTSUPPORTEDCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="HEALEDCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="COMMENTDATA" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="nodes">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="node">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                       &lt;element name="SUITEREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="HOSTNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="PORT" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                                       &lt;element name="SCRIPTCOUNT" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="scriptSummaries">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="summary" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;choice maxOccurs="unbounded" minOccurs="0">
     *                             &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                             &lt;element name="SCRIPTREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="OUTPUT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ARTIFACT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="SCREENSHOT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="SCRIPTNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="SUITENAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="SUITEREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="TOTALSTEPS" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                             &lt;element name="FAILURES" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="ERRORS" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="TIMETAKEN" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="NODEHOST" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="NODEPORT" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                             &lt;element name="SCRIPTSTATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="LOADCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="TCCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="TCPASSED" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="TCFAILED" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="SCRIPTRELPATH" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="STARTURL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *                             &lt;element name="LAUNCHERID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="SCRIPTARGS" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="STARTTIME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="SUITEID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="SUITEINFO" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/choice>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="testCaseSummaries">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="testCaseSummary" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                             &lt;element name="TESTCASEREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="SCRIPTREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="SUITEREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="TCSTATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="TIMETAKEN" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="SCRIPTNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="FAILUREMESSAGE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "suiteSummary",
        "scriptSummaries",
        "testCaseSummaries"
    })
    public static class Suite {

        @XmlElement(required = true)
        protected Suites.Suite.SuiteSummary suiteSummary;
        @XmlElement(required = true)
        protected Suites.Suite.ScriptSummaries scriptSummaries;
        @XmlElement(required = true)
        protected Suites.Suite.TestCaseSummaries testCaseSummaries;

        /**
         * Gets the value of the suiteSummary property.
         * 
         * @return
         *     possible object is
         *     {@link Suites.Suite.SuiteSummary }
         *     
         */
        public Suites.Suite.SuiteSummary getSuiteSummary() {
            return suiteSummary;
        }

        /**
         * Sets the value of the suiteSummary property.
         * 
         * @param value
         *     allowed object is
         *     {@link Suites.Suite.SuiteSummary }
         *     
         */
        public void setSuiteSummary(Suites.Suite.SuiteSummary value) {
            this.suiteSummary = value;
        }

        /**
         * Gets the value of the scriptSummaries property.
         * 
         * @return
         *     possible object is
         *     {@link Suites.Suite.ScriptSummaries }
         *     
         */
        public Suites.Suite.ScriptSummaries getScriptSummaries() {
            return scriptSummaries;
        }

        /**
         * Sets the value of the scriptSummaries property.
         * 
         * @param value
         *     allowed object is
         *     {@link Suites.Suite.ScriptSummaries }
         *     
         */
        public void setScriptSummaries(Suites.Suite.ScriptSummaries value) {
            this.scriptSummaries = value;
        }

        /**
         * Gets the value of the testCaseSummaries property.
         * 
         * @return
         *     possible object is
         *     {@link Suites.Suite.TestCaseSummaries }
         *     
         */
        public Suites.Suite.TestCaseSummaries getTestCaseSummaries() {
            return testCaseSummaries;
        }

        /**
         * Sets the value of the testCaseSummaries property.
         * 
         * @param value
         *     allowed object is
         *     {@link Suites.Suite.TestCaseSummaries }
         *     
         */
        public void setTestCaseSummaries(Suites.Suite.TestCaseSummaries value) {
            this.testCaseSummaries = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="summary" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
         *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *                   &lt;element name="SCRIPTREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="OUTPUT" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ARTIFACT" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="SCREENSHOT" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="SCRIPTNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="SUITENAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="SUITEREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="TOTALSTEPS" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *                   &lt;element name="FAILURES" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="ERRORS" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="TIMETAKEN" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="NODEHOST" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="NODEPORT" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *                   &lt;element name="SCRIPTSTATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="LOADCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="TCCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="TCPASSED" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="TCFAILED" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="SCRIPTRELPATH" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="STARTURL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
         *                   &lt;element name="LAUNCHERID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="SCRIPTARGS" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="STARTTIME" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="SUITEID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="SUITEINFO" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/choice>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "summary"
        })
        public static class ScriptSummaries {

            protected List<Suites.Suite.ScriptSummaries.Summary> summary;

            /**
             * Gets the value of the summary property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the summary property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSummary().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Suites.Suite.ScriptSummaries.Summary }
             * 
             * 
             */
            public List<Suites.Suite.ScriptSummaries.Summary> getSummary() {
                if (summary == null) {
                    summary = new ArrayList<Suites.Suite.ScriptSummaries.Summary>();
                }
                return this.summary;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;choice maxOccurs="unbounded" minOccurs="0">
             *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}short"/>
             *         &lt;element name="SCRIPTREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="OUTPUT" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ARTIFACT" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="SCREENSHOT" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="SCRIPTNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="SUITENAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="SUITEREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="TOTALSTEPS" type="{http://www.w3.org/2001/XMLSchema}short"/>
             *         &lt;element name="FAILURES" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="ERRORS" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="TIMETAKEN" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="NODEHOST" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="NODEPORT" type="{http://www.w3.org/2001/XMLSchema}short"/>
             *         &lt;element name="SCRIPTSTATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="LOADCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="TCCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="TCPASSED" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="TCFAILED" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="SCRIPTRELPATH" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="STARTURL" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
             *         &lt;element name="LAUNCHERID" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="SCRIPTARGS" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="STARTTIME" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="SUITEID" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="SUITEINFO" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/choice>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "idOrSCRIPTREPORTIDOrOUTPUT"
            })
            public static class Summary {

                @XmlElementRefs({
                    @XmlElementRef(name = "SUITENAME", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "ID", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "NODEHOST", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "SCRIPTSTATUS", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "SUITEREPORTID", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "LOADCOUNT", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "STARTURL", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "OUTPUT", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "SCRIPTNAME", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "SCRIPTRELPATH", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "ERRORS", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "TOTALSTEPS", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "TCFAILED", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "SUITEID", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "STARTTIME", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "FAILURES", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "TIMETAKEN", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "SCRIPTREPORTID", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "ARTIFACT", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "LAUNCHERID", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "SCREENSHOT", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "SCRIPTARGS", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "NODEPORT", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "TCCOUNT", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "TCPASSED", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "SUITEINFO", type = JAXBElement.class, required = false)
                })
                protected List<JAXBElement<? extends Serializable>> idOrSCRIPTREPORTIDOrOUTPUT;

                /**
                 * Gets the value of the idOrSCRIPTREPORTIDOrOUTPUT property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the idOrSCRIPTREPORTIDOrOUTPUT property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getIDOrSCRIPTREPORTIDOrOUTPUT().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link Short }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link Byte }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link Byte }{@code >}
                 * {@link JAXBElement }{@code <}{@link Short }{@code >}
                 * {@link JAXBElement }{@code <}{@link Byte }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link Byte }{@code >}
                 * {@link JAXBElement }{@code <}{@link Integer }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link Short }{@code >}
                 * {@link JAXBElement }{@code <}{@link Byte }{@code >}
                 * {@link JAXBElement }{@code <}{@link Byte }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * 
                 * 
                 */
                public List<JAXBElement<? extends Serializable>> getIDOrSCRIPTREPORTIDOrOUTPUT() {
                    if (idOrSCRIPTREPORTIDOrOUTPUT == null) {
                        idOrSCRIPTREPORTIDOrOUTPUT = new ArrayList<JAXBElement<? extends Serializable>>();
                    }
                    return this.idOrSCRIPTREPORTIDOrOUTPUT;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="SUITEREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SUITENAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SUITEPATH" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="STARTTIME" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ENDTIME" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SUITESTATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="TOTALCOUNT" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="PASSEDCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="FAILEDCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="TIMETAKEN" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="BROWSERTYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SUITEINFO" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="USERDEFINEDID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="TCCOUNT" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="TCPASSED" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="TCFAILED" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="MACHINENAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="PARENTSUITEID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SKIPPEDCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="ABORTEDCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="ORIGINALPATH" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ANDROIDDEVICE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="IOSDEVICE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="NOTSUPPORTEDCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="HEALEDCOUNT" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="COMMENTDATA" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="nodes">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="node">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                             &lt;element name="SUITEREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="HOSTNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="PORT" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *                             &lt;element name="SCRIPTCOUNT" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "suitereportid",
            "suitename",
            "suitepath",
            "starttime",
            "endtime",
            "suitestatus",
            "totalcount",
            "passedcount",
            "failedcount",
            "timetaken",
            "browsertype",
            "suiteinfo",
            "userdefinedid",
            "tccount",
            "tcpassed",
            "tcfailed",
            "machinename",
            "parentsuiteid",
            "skippedcount",
            "abortedcount",
            "originalpath",
            "androiddevice",
            "iosdevice",
            "notsupportedcount",
            "healedcount",
            "commentdata",
            "nodes"
        })
        public static class SuiteSummary {

            @XmlElement(name = "ID")
            protected byte id;
            @XmlElement(name = "SUITEREPORTID", required = true)
            protected String suitereportid;
            @XmlElement(name = "SUITENAME", required = true)
            protected String suitename;
            @XmlElement(name = "SUITEPATH", required = true)
            protected String suitepath;
            @XmlElement(name = "STARTTIME", required = true)
            protected String starttime;
            @XmlElement(name = "ENDTIME", required = true)
            protected String endtime;
            @XmlElement(name = "SUITESTATUS", required = true)
            protected String suitestatus;
            @XmlElement(name = "TOTALCOUNT")
            protected short totalcount;
            @XmlElement(name = "PASSEDCOUNT")
            protected byte passedcount;
            @XmlElement(name = "FAILEDCOUNT")
            protected byte failedcount;
            @XmlElement(name = "TIMETAKEN")
            protected int timetaken;
            @XmlElement(name = "BROWSERTYPE", required = true)
            protected String browsertype;
            @XmlElement(name = "SUITEINFO", required = true)
            protected String suiteinfo;
            @XmlElement(name = "USERDEFINEDID", required = true)
            protected String userdefinedid;
            @XmlElement(name = "TCCOUNT")
            protected short tccount;
            @XmlElement(name = "TCPASSED")
            protected byte tcpassed;
            @XmlElement(name = "TCFAILED")
            protected short tcfailed;
            @XmlElement(name = "MACHINENAME", required = true)
            protected String machinename;
            @XmlElement(name = "PARENTSUITEID", required = true)
            protected String parentsuiteid;
            @XmlElement(name = "SKIPPEDCOUNT")
            protected byte skippedcount;
            @XmlElement(name = "ABORTEDCOUNT")
            protected byte abortedcount;
            @XmlElement(name = "ORIGINALPATH", required = true)
            protected String originalpath;
            @XmlElement(name = "ANDROIDDEVICE", required = true)
            protected String androiddevice;
            @XmlElement(name = "IOSDEVICE", required = true)
            protected String iosdevice;
            @XmlElement(name = "NOTSUPPORTEDCOUNT")
            protected byte notsupportedcount;
            @XmlElement(name = "HEALEDCOUNT")
            protected byte healedcount;
            @XmlElement(name = "COMMENTDATA", required = true)
            protected String commentdata;
            @XmlElement(required = true)
            protected Suites.Suite.SuiteSummary.Nodes nodes;

            /**
             * Gets the value of the id property.
             * 
             */
            public byte getID() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setID(byte value) {
                this.id = value;
            }

            /**
             * Gets the value of the suitereportid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSUITEREPORTID() {
                return suitereportid;
            }

            /**
             * Sets the value of the suitereportid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSUITEREPORTID(String value) {
                this.suitereportid = value;
            }

            /**
             * Gets the value of the suitename property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSUITENAME() {
                return suitename;
            }

            /**
             * Sets the value of the suitename property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSUITENAME(String value) {
                this.suitename = value;
            }

            /**
             * Gets the value of the suitepath property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSUITEPATH() {
                return suitepath;
            }

            /**
             * Sets the value of the suitepath property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSUITEPATH(String value) {
                this.suitepath = value;
            }

            /**
             * Gets the value of the starttime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSTARTTIME() {
                return starttime;
            }

            /**
             * Sets the value of the starttime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSTARTTIME(String value) {
                this.starttime = value;
            }

            /**
             * Gets the value of the endtime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getENDTIME() {
                return endtime;
            }

            /**
             * Sets the value of the endtime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setENDTIME(String value) {
                this.endtime = value;
            }

            /**
             * Gets the value of the suitestatus property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSUITESTATUS() {
                return suitestatus;
            }

            /**
             * Sets the value of the suitestatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSUITESTATUS(String value) {
                this.suitestatus = value;
            }

            /**
             * Gets the value of the totalcount property.
             * 
             */
            public short getTOTALCOUNT() {
                return totalcount;
            }

            /**
             * Sets the value of the totalcount property.
             * 
             */
            public void setTOTALCOUNT(short value) {
                this.totalcount = value;
            }

            /**
             * Gets the value of the passedcount property.
             * 
             */
            public byte getPASSEDCOUNT() {
                return passedcount;
            }

            /**
             * Sets the value of the passedcount property.
             * 
             */
            public void setPASSEDCOUNT(byte value) {
                this.passedcount = value;
            }

            /**
             * Gets the value of the failedcount property.
             * 
             */
            public byte getFAILEDCOUNT() {
                return failedcount;
            }

            /**
             * Sets the value of the failedcount property.
             * 
             */
            public void setFAILEDCOUNT(byte value) {
                this.failedcount = value;
            }

            /**
             * Gets the value of the timetaken property.
             * 
             */
            public int getTIMETAKEN() {
                return timetaken;
            }

            /**
             * Sets the value of the timetaken property.
             * 
             */
            public void setTIMETAKEN(int value) {
                this.timetaken = value;
            }

            /**
             * Gets the value of the browsertype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBROWSERTYPE() {
                return browsertype;
            }

            /**
             * Sets the value of the browsertype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBROWSERTYPE(String value) {
                this.browsertype = value;
            }

            /**
             * Gets the value of the suiteinfo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSUITEINFO() {
                return suiteinfo;
            }

            /**
             * Sets the value of the suiteinfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSUITEINFO(String value) {
                this.suiteinfo = value;
            }

            /**
             * Gets the value of the userdefinedid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUSERDEFINEDID() {
                return userdefinedid;
            }

            /**
             * Sets the value of the userdefinedid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUSERDEFINEDID(String value) {
                this.userdefinedid = value;
            }

            /**
             * Gets the value of the tccount property.
             * 
             */
            public short getTCCOUNT() {
                return tccount;
            }

            /**
             * Sets the value of the tccount property.
             * 
             */
            public void setTCCOUNT(short value) {
                this.tccount = value;
            }

            /**
             * Gets the value of the tcpassed property.
             * 
             */
            public byte getTCPASSED() {
                return tcpassed;
            }

            /**
             * Sets the value of the tcpassed property.
             * 
             */
            public void setTCPASSED(byte value) {
                this.tcpassed = value;
            }

            /**
             * Gets the value of the tcfailed property.
             * 
             */
            public short getTCFAILED() {
                return tcfailed;
            }

            /**
             * Sets the value of the tcfailed property.
             * 
             */
            public void setTCFAILED(short value) {
                this.tcfailed = value;
            }

            /**
             * Gets the value of the machinename property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMACHINENAME() {
                return machinename;
            }

            /**
             * Sets the value of the machinename property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMACHINENAME(String value) {
                this.machinename = value;
            }

            /**
             * Gets the value of the parentsuiteid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPARENTSUITEID() {
                return parentsuiteid;
            }

            /**
             * Sets the value of the parentsuiteid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPARENTSUITEID(String value) {
                this.parentsuiteid = value;
            }

            /**
             * Gets the value of the skippedcount property.
             * 
             */
            public byte getSKIPPEDCOUNT() {
                return skippedcount;
            }

            /**
             * Sets the value of the skippedcount property.
             * 
             */
            public void setSKIPPEDCOUNT(byte value) {
                this.skippedcount = value;
            }

            /**
             * Gets the value of the abortedcount property.
             * 
             */
            public byte getABORTEDCOUNT() {
                return abortedcount;
            }

            /**
             * Sets the value of the abortedcount property.
             * 
             */
            public void setABORTEDCOUNT(byte value) {
                this.abortedcount = value;
            }

            /**
             * Gets the value of the originalpath property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getORIGINALPATH() {
                return originalpath;
            }

            /**
             * Sets the value of the originalpath property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setORIGINALPATH(String value) {
                this.originalpath = value;
            }

            /**
             * Gets the value of the androiddevice property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getANDROIDDEVICE() {
                return androiddevice;
            }

            /**
             * Sets the value of the androiddevice property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setANDROIDDEVICE(String value) {
                this.androiddevice = value;
            }

            /**
             * Gets the value of the iosdevice property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIOSDEVICE() {
                return iosdevice;
            }

            /**
             * Sets the value of the iosdevice property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIOSDEVICE(String value) {
                this.iosdevice = value;
            }

            /**
             * Gets the value of the notsupportedcount property.
             * 
             */
            public byte getNOTSUPPORTEDCOUNT() {
                return notsupportedcount;
            }

            /**
             * Sets the value of the notsupportedcount property.
             * 
             */
            public void setNOTSUPPORTEDCOUNT(byte value) {
                this.notsupportedcount = value;
            }

            /**
             * Gets the value of the healedcount property.
             * 
             */
            public byte getHEALEDCOUNT() {
                return healedcount;
            }

            /**
             * Sets the value of the healedcount property.
             * 
             */
            public void setHEALEDCOUNT(byte value) {
                this.healedcount = value;
            }

            /**
             * Gets the value of the commentdata property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCOMMENTDATA() {
                return commentdata;
            }

            /**
             * Sets the value of the commentdata property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCOMMENTDATA(String value) {
                this.commentdata = value;
            }

            /**
             * Gets the value of the nodes property.
             * 
             * @return
             *     possible object is
             *     {@link Suites.Suite.SuiteSummary.Nodes }
             *     
             */
            public Suites.Suite.SuiteSummary.Nodes getNodes() {
                return nodes;
            }

            /**
             * Sets the value of the nodes property.
             * 
             * @param value
             *     allowed object is
             *     {@link Suites.Suite.SuiteSummary.Nodes }
             *     
             */
            public void setNodes(Suites.Suite.SuiteSummary.Nodes value) {
                this.nodes = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="node">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                   &lt;element name="SUITEREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="HOSTNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="PORT" type="{http://www.w3.org/2001/XMLSchema}short"/>
             *                   &lt;element name="SCRIPTCOUNT" type="{http://www.w3.org/2001/XMLSchema}short"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "node"
            })
            public static class Nodes {

                @XmlElement(required = true)
                protected Suites.Suite.SuiteSummary.Nodes.Node node;

                /**
                 * Gets the value of the node property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Suites.Suite.SuiteSummary.Nodes.Node }
                 *     
                 */
                public Suites.Suite.SuiteSummary.Nodes.Node getNode() {
                    return node;
                }

                /**
                 * Sets the value of the node property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Suites.Suite.SuiteSummary.Nodes.Node }
                 *     
                 */
                public void setNode(Suites.Suite.SuiteSummary.Nodes.Node value) {
                    this.node = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *         &lt;element name="SUITEREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="HOSTNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="PORT" type="{http://www.w3.org/2001/XMLSchema}short"/>
                 *         &lt;element name="SCRIPTCOUNT" type="{http://www.w3.org/2001/XMLSchema}short"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "id",
                    "suitereportid",
                    "hostname",
                    "port",
                    "scriptcount"
                })
                public static class Node {

                    @XmlElement(name = "ID")
                    protected byte id;
                    @XmlElement(name = "SUITEREPORTID", required = true)
                    protected String suitereportid;
                    @XmlElement(name = "HOSTNAME", required = true)
                    protected String hostname;
                    @XmlElement(name = "PORT")
                    protected short port;
                    @XmlElement(name = "SCRIPTCOUNT")
                    protected short scriptcount;

                    /**
                     * Gets the value of the id property.
                     * 
                     */
                    public byte getID() {
                        return id;
                    }

                    /**
                     * Sets the value of the id property.
                     * 
                     */
                    public void setID(byte value) {
                        this.id = value;
                    }

                    /**
                     * Gets the value of the suitereportid property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getSUITEREPORTID() {
                        return suitereportid;
                    }

                    /**
                     * Sets the value of the suitereportid property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setSUITEREPORTID(String value) {
                        this.suitereportid = value;
                    }

                    /**
                     * Gets the value of the hostname property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getHOSTNAME() {
                        return hostname;
                    }

                    /**
                     * Sets the value of the hostname property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setHOSTNAME(String value) {
                        this.hostname = value;
                    }

                    /**
                     * Gets the value of the port property.
                     * 
                     */
                    public short getPORT() {
                        return port;
                    }

                    /**
                     * Sets the value of the port property.
                     * 
                     */
                    public void setPORT(short value) {
                        this.port = value;
                    }

                    /**
                     * Gets the value of the scriptcount property.
                     * 
                     */
                    public short getSCRIPTCOUNT() {
                        return scriptcount;
                    }

                    /**
                     * Sets the value of the scriptcount property.
                     * 
                     */
                    public void setSCRIPTCOUNT(short value) {
                        this.scriptcount = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="testCaseSummary" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *                   &lt;element name="TESTCASEREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="SCRIPTREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="SUITEREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="TCSTATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="TIMETAKEN" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="SCRIPTNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="FAILUREMESSAGE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "testCaseSummary"
        })
        public static class TestCaseSummaries {

            protected List<Suites.Suite.TestCaseSummaries.TestCaseSummary> testCaseSummary;

            /**
             * Gets the value of the testCaseSummary property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the testCaseSummary property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTestCaseSummary().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Suites.Suite.TestCaseSummaries.TestCaseSummary }
             * 
             * 
             */
            public List<Suites.Suite.TestCaseSummaries.TestCaseSummary> getTestCaseSummary() {
                if (testCaseSummary == null) {
                    testCaseSummary = new ArrayList<Suites.Suite.TestCaseSummaries.TestCaseSummary>();
                }
                return this.testCaseSummary;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}short"/>
             *         &lt;element name="TESTCASEREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="SCRIPTREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="SUITEREPORTID" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="TCSTATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="TIMETAKEN" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="SCRIPTNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="FAILUREMESSAGE" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "id",
                "testcasereportid",
                "scriptreportid",
                "suitereportid",
                "description",
                "tcstatus",
                "timetaken",
                "scriptname",
                "failuremessage"
            })
            public static class TestCaseSummary {

                @XmlElement(name = "ID")
                protected short id;
                @XmlElement(name = "TESTCASEREPORTID", required = true)
                protected String testcasereportid;
                @XmlElement(name = "SCRIPTREPORTID", required = true)
                protected String scriptreportid;
                @XmlElement(name = "SUITEREPORTID", required = true)
                protected String suitereportid;
                @XmlElement(name = "DESCRIPTION", required = true)
                protected String description;
                @XmlElement(name = "TCSTATUS", required = true)
                protected String tcstatus;
                @XmlElement(name = "TIMETAKEN")
                protected int timetaken;
                @XmlElement(name = "SCRIPTNAME", required = true)
                protected String scriptname;
                @XmlElement(name = "FAILUREMESSAGE", required = true)
                protected String failuremessage;

                /**
                 * Gets the value of the id property.
                 * 
                 */
                public short getID() {
                    return id;
                }

                /**
                 * Sets the value of the id property.
                 * 
                 */
                public void setID(short value) {
                    this.id = value;
                }

                /**
                 * Gets the value of the testcasereportid property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTESTCASEREPORTID() {
                    return testcasereportid;
                }

                /**
                 * Sets the value of the testcasereportid property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTESTCASEREPORTID(String value) {
                    this.testcasereportid = value;
                }

                /**
                 * Gets the value of the scriptreportid property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSCRIPTREPORTID() {
                    return scriptreportid;
                }

                /**
                 * Sets the value of the scriptreportid property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSCRIPTREPORTID(String value) {
                    this.scriptreportid = value;
                }

                /**
                 * Gets the value of the suitereportid property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSUITEREPORTID() {
                    return suitereportid;
                }

                /**
                 * Sets the value of the suitereportid property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSUITEREPORTID(String value) {
                    this.suitereportid = value;
                }

                /**
                 * Gets the value of the description property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDESCRIPTION() {
                    return description;
                }

                /**
                 * Sets the value of the description property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDESCRIPTION(String value) {
                    this.description = value;
                }

                /**
                 * Gets the value of the tcstatus property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTCSTATUS() {
                    return tcstatus;
                }

                /**
                 * Sets the value of the tcstatus property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTCSTATUS(String value) {
                    this.tcstatus = value;
                }

                /**
                 * Gets the value of the timetaken property.
                 * 
                 */
                public int getTIMETAKEN() {
                    return timetaken;
                }

                /**
                 * Sets the value of the timetaken property.
                 * 
                 */
                public void setTIMETAKEN(int value) {
                    this.timetaken = value;
                }

                /**
                 * Gets the value of the scriptname property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSCRIPTNAME() {
                    return scriptname;
                }

                /**
                 * Sets the value of the scriptname property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSCRIPTNAME(String value) {
                    this.scriptname = value;
                }

                /**
                 * Gets the value of the failuremessage property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFAILUREMESSAGE() {
                    return failuremessage;
                }

                /**
                 * Sets the value of the failuremessage property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFAILUREMESSAGE(String value) {
                    this.failuremessage = value;
                }

            }

        }

    }

}
