//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.14 at 12:03:36 PM IST 
//
package com.infosys.utilities.checkstyle;

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class ObjectFactory {
	public Checkstyle createCheckstyle() {
		return new Checkstyle();
	}

	public Checkstyle.File createCheckstyleFile() {
		return new Checkstyle.File();
	}

	public Checkstyle.File.Error createCheckstyleFileError() {
		return new Checkstyle.File.Error();
	}
}
