//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.04 at 07:58:33 PM IST 
//
package com.infosys.utilities.pythonut;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "testcase", "systemOut", "systemErr" })
@XmlRootElement(name = "testsuite")
public class Testsuite {
	@XmlElement(required = true)
	protected List<Testsuite.Testcase> testcase;
	@XmlElement(name = "system-out", required = true)
	protected String systemOut;
	@XmlElement(name = "system-err", required = true)
	protected String systemErr;
	@XmlAttribute(name = "errors")
	protected Integer errors;
	@XmlAttribute(name = "failures")
	protected Integer failures;
	@XmlAttribute(name = "name")
	protected String name;
	@XmlAttribute(name = "tests")
	protected Integer tests;
	@XmlAttribute(name = "time")
	protected BigDecimal time;

	public List<Testsuite.Testcase> getTestcase() {
		if (testcase == null) {
			testcase = new ArrayList<Testsuite.Testcase>();
		}
		return this.testcase;
	}

	public String getSystemOut() {
		return systemOut;
	}

	public void setSystemOut(String value) {
		this.systemOut = value;
	}

	public String getSystemErr() {
		return systemErr;
	}

	public void setSystemErr(String value) {
		this.systemErr = value;
	}

	public Integer getErrors() {
		return errors;
	}

	public void setErrors(Integer value) {
		this.errors = value;
	}

	public Integer getFailures() {
		return failures;
	}

	public void setFailures(Integer value) {
		this.failures = value;
	}

	public String getName() {
		return name;
	}

	public void setName(String value) {
		this.name = value;
	}

	public Integer getTests() {
		return tests;
	}

	public void setTests(Integer value) {
		this.tests = value;
	}

	public BigDecimal getTime() {
		return time;
	}

	public void setTime(BigDecimal value) {
		this.time = value;
	}

	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "failure", "error" })
	public static class Testcase {
		@XmlElement(required = true)
		protected Testsuite.Testcase.Failure failure;
		@XmlElement(required = true)
		protected Testsuite.Testcase.Error error;
		@XmlAttribute(name = "classname")
		protected String classname;
		@XmlAttribute(name = "name")
		protected String name;
		@XmlAttribute(name = "time")
		protected BigDecimal time;

		public Testsuite.Testcase.Failure getFailure() {
			return failure;
		}

		public void setFailure(Testsuite.Testcase.Failure value) {
			this.failure = value;
		}

		public Testsuite.Testcase.Error getError() {
			return error;
		}

		public void setError(Testsuite.Testcase.Error value) {
			this.error = value;
		}

		public String getClassname() {
			return classname;
		}

		public void setClassname(String value) {
			this.classname = value;
		}

		public String getName() {
			return name;
		}

		public void setName(String value) {
			this.name = value;
		}

		public BigDecimal getTime() {
			return time;
		}

		public void setTime(BigDecimal value) {
			this.time = value;
		}

		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class Error {
			@XmlAttribute(name = "message")
			protected String message;
			@XmlAttribute(name = "type")
			protected String type;

			public String getMessage() {
				return message;
			}

			public void setMessage(String value) {
				this.message = value;
			}

			public String getType() {
				return type;
			}

			public void setType(String value) {
				this.type = value;
			}
		}

		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "")
		public static class Failure {
			@XmlAttribute(name = "message")
			protected String message;
			@XmlAttribute(name = "type")
			protected String type;

			public String getMessage() {
				return message;
			}

			public void setMessage(String value) {
				this.message = value;
			}

			public String getType() {
				return type;
			}

			public void setType(String value) {
				this.type = value;
			}
		}
	}
}
