//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.13 at 11:15:25 AM IST 
//
package com.infosys.utilities.coberturago;

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class ObjectFactory {
	public Coverage createCoverage() {
		return new Coverage();
	}

	public Coverage.Packages createCoveragePackages() {
		return new Coverage.Packages();
	}

	public Coverage.Packages.Package createCoveragePackagesPackage() {
		return new Coverage.Packages.Package();
	}

	public Coverage.Packages.Package.Classes createCoveragePackagesPackageClasses() {
		return new Coverage.Packages.Package.Classes();
	}

	public Coverage.Packages.Package.Classes.Class createCoveragePackagesPackageClassesClass() {
		return new Coverage.Packages.Package.Classes.Class();
	}

	public Coverage.Packages.Package.Classes.Class.Lines createCoveragePackagesPackageClassesClassLines() {
		return new Coverage.Packages.Package.Classes.Class.Lines();
	}

	public Coverage.Packages.Package.Classes.Class.Methods createCoveragePackagesPackageClassesClassMethods() {
		return new Coverage.Packages.Package.Classes.Class.Methods();
	}

	public Coverage.Packages.Package.Classes.Class.Methods.Method createCoveragePackagesPackageClassesClassMethodsMethod() {
		return new Coverage.Packages.Package.Classes.Class.Methods.Method();
	}

	public Coverage.Packages.Package.Classes.Class.Methods.Method.Lines createCoveragePackagesPackageClassesClassMethodsMethodLines() {
		return new Coverage.Packages.Package.Classes.Class.Methods.Method.Lines();
	}

	public Coverage.Packages.Package.Classes.Class.Lines.Line createCoveragePackagesPackageClassesClassLinesLine() {
		return new Coverage.Packages.Package.Classes.Class.Lines.Line();
	}

	public Coverage.Packages.Package.Classes.Class.Methods.Method.Lines.Line createCoveragePackagesPackageClassesClassMethodsMethodLinesLine() {
		return new Coverage.Packages.Package.Classes.Class.Methods.Method.Lines.Line();
	}
}
